### ISSUE TITLE
Enable Travis builds

### ISSUE THREAD

**Issue by dtolnay** [laumann/compiletest-rs#138]
This repo contains a .travis.yml but https://travis-ci.org/laumann/compiletest-rs is currently showing no builds. I believe @laumann will need to flip a switch in https://travis-ci.org/account/repositories.

**Comment by laumann** [comment]
I've enabled Travis. I remember I was a little concerned will the permissions that Travis wanted. I don't remember AppVeyor wanting that much. But we should be able to set it up now.

I had a question in #97 that I never got answered: Could the AppVeyor builds not be extended to run the tests in test-project, instead of creating a Travis build?

**Comment by dtolnay** [comment]
Travis has always had a better user experience than AppVeyor in my experience. I stick to Travis as primary CI, adding AppVeyor only if I need to build on Windows. Travis [recently announced Windows support](https://blog.travis-ci.com/2018-10-11-windows-early-release) so I may be dropping AppVeyor altogether.
