### ISSUE TITLE
"unexpected "error": '8:1: 8:33: multiple matching crates for `deny_public_fields` [E0464]'" after Cargo update

### ISSUE THREAD

**Issue by SimonSapin** [laumann/compiletest-rs#62]
Servo’s CI failed after updating Cargo: https://github.com/servo/servo/pull/16601#issuecomment-297000204

CC @nox

I suspect that the issue is using `-L path/to/directory` whereas Cargo uses `--extern name=path/to/file.rlib`. I tried to reproduce outside of Servo but failed.

Attempted steps:

* `rustup update nightly`
* `rustup update nightly-2017-04-21`
* Use this branch https://github.com/laumann/compiletest-rs/compare/master...SimonSapin:dep
* `cd test-project`
* `cargo +nightly test`
* `cargo +nightly-2017-04-21 test`

**Comment by laumann** [comment]
I'm not sure what to do about this. If the issue is using `--extern` instead of `-L` then maybe https://github.com/servo/servo/blob/234951e4b6d66891cd0cc9705f42e3ca16d9e3d5/tests/compiletest/helper/lib.rs#L26 needs changing.

But if there are multiple matching crates, does that mean that Cargo started adding dependencies that weren't added before? Maybe the dependencies added with `config.target_rustcflags` is obsolete?

**Comment by SimonSapin** [comment]
I filed this in case you had another idea, but unfortunately I believe there isn’t much to do as long as `compiletest-rs` works by calling `rustc`. To properly work with Cargo’s dependency management it should generate `Cargo.toml` files and call `cargo` instead, but that’s beyond a mere bugfix and almost sounds like a rewrite.
